### ISSUE TITLE
Will this app with external network?

### ISSUE THREAD

**Issue by sheminasalam** [bds89/miner2android#1]
If the mobile device is connected to external network than the network in which the farm is working, will this app continue to work or is it mandatory that this app needs to be connected to the local network always?

**Comment by bds89** [comment]
This is possible if your ISP provides a static IP. To do this, you need to open the port in your router that is specified in the PORT_FLASK: 5000 config and access your rig using your external IP. I use this option, it is the easiest, but not the safest, because. access to your rig is protected only by your PASS specified in the config (maybe it's worth adding a blocking for a user who enters the wrong password 3 times, I also plan to add notifications about authorization error).

There may be other options, such as:
The application makes a request "http://{your_ip_adress}:{your_port}. Therefore, instead of the IP address, you can specify a string - the address of your domain. To get the domain address, you can use the free duckdns installed on the router, success also depends on your Internet provider, which something similar was discussed here: https://community.home-assistant.io/t/remote-access-without-dedicated-static-ip/81405/18

The same is true in Home Assistant, in its application you enter the address of your HA server.
But if you use Home Assistant Cloud, everything works at the expense of an intermediate server between your home and your phone, I don’t have such a server (.

**Comment by bds89** [comment]
If you have several computers, you just need to get access from the external network to one of them, the application will connect to the rest through this computer.
This computer may not be your mining rig, but any Linux/Windows computer.
To do this, on other computers, add the SLAVE_PC: true parameter to the config. In the application, enter the IP address of your open computer, set the use as gateway flag, and enter the internal IP address of your second computer.

**Comment by sheminasalam** [comment]
My ISP doesn't support static IP and so I use cloudflare argo tunnel to expose my HA. But in that case instead of IP address for website, a cloudflare web url is provided or if we have own url, it can be used. Can this app be configured to look into such a url?

**Comment by bds89** [comment]
I think it will be possible to add such support, instead of the IP address you will need to enter your URL. I'll try see into cloudflare, but later, now while I'm trying to add notifications to this application, because without notifications it's useless, it's easier to use Home Assistant.
